import org.gradle.internal.impldep.com.google.common.io.Files

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}
val getTheFileAsArtifact by configurations.registering

dependencies {
    api(project(":list"))
    getTheFileAsArtifact(project(":list","asArtifact"))
}



tasks.register("explode"){
    inputs.files(getTheFileAsArtifact)
    //the line here explodes afterEvaluate in :list
    val singleFile = getTheFileAsArtifact.get().singleFile
    doFirst {
        println("we dont get here... " + singleFile)
    }
}
