/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
    //id ("ivy-publish") since ivy-publish uses afterEvaluate, same explosion
}
//if this wouldnt be here it work...but cant easily avoid it, see  used by publishing for example
project.afterEvaluate{}

val myFile by configurations.registering{
    isCanBeResolved=false
    isCanBeConsumed=true
}
dependencies{
    //as seen on https://docs.gradle.org/current/userguide/declaring_dependencies.html#ex-declaring-multiple-file-dependencies
    myFile(project.files("Hello"))
}
